name: windows-net5.0

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.*
        
    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --no-restore

    - name: Test x86
      run: dotnet test --verbosity normal --framework net5.0 --runtime win-x86
      working-directory: LevelDB.Tests/
      
    - name: Test x64
      run: dotnet test --verbosity normal --framework net5.0 --runtime win-x64
      working-directory: LevelDB.Tests/
