name: Publish packages

on:
  workflow_dispatch:

jobs:
  build:

    runs-on: windows-latest
    environment: Nuget

    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Restore dependencies
      run: dotnet restore
      working-directory: ${{env.GITHUB_WORKSPACE}}

    - name: Build
      run: dotnet build --configuration Release --no-restore
      working-directory: ${{env.GITHUB_WORKSPACE}}

    - name: Publish SoftFX.LevelDB.Standard
      uses: brandedoutcast/publish-nuget@v2.5.2
      with:
          PROJECT_FILE_PATH: LevelDB.NET/LevelDB.NET.csproj
          NUGET_KEY: ${{secrets.NUGET_KEY}}
