name: Linux

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
        
    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build -a linux-x64 -c RELEASE --no-restore
    
    - name: Test x64
      run: dotnet test --no-build --verbosity normal 
      working-directory: LevelDB.Tests/bin/RELEASE/net5.0/LevelDB.NET.Tests.dll
